events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 4443 ssl;
        server_name ai2god.club;  # 替换为你的域名

        ssl_certificate ./nssl/ai2god.club.crt;
        ssl_certificate_key ./nssl/ai2god.club.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512;
        ssl_prefer_server_ciphers off;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ =404;
        }
    }

    server {
        listen 4443 ssl;
        server_name www.ai2god.club;  # 替换为你的域名

        ssl_certificate ./nssl/www.ai2god.club.crt;
        ssl_certificate_key ./nssl/www.ai2god.club.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512;
        ssl_prefer_server_ciphers off;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ =404;
        }
    }

    # 自动将 HTTP 跳转到 HTTPS
    server {
        listen 881;
        server_name ai2god.club www.ai2god.club;
        return 301 https://$host$request_uri;
    }
}
